name: s3-get-object
description: 'Get object from AWS S3'
inputs:
  bucket:
    description: 'S3 Bucket'
    required: true
  aws-access-key:
    description: 'AWS Access Key'
    required: true
outputs:
  message: 
    description: 'Ouput message'
runs:
  using: 'node12'
  main: 'index.js'