name: 'S3 Get Object'
description: 'Get object from AWS S3'
inputs:
  bucket:
    description: 'S3 Bucket'
    required: true
  region:
    description: 'S3 Region'
    required: true
  aws-access-key:
    description: 'AWS Access Key'
    required: true
  aws-secret-key: 
    description: 'AWS Secret Key'
    required: true
  object-key: 
    description: 'S3 Object Key'
    required: true
  filename: 
    description: 'Filename of the file when gets saved'
    required: true

outputs:
  message: 
    description: 'Ouput message'

runs:
  using: 'node12'
  main: 'dist/index.js'