on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    name: Gets S3 Object
    steps:
      - name:  Getting S3 Object
        id: s3
        uses: jcfrane/s3-get-object-action@v1.0
        with:
          region: ap-southeast-1
          bucket: ${{ secrets.BUCKET }}
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
          object-key: build-artifacts/prod.yml
          filename: prod.yml
      - name : Check file
        run: |
          ls -la
          cat prod.yml
      - name: Get s3 details
        run: echo "Contents ${{ steps.s3.outputs.message }}"